// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stone.Lancamentos.INFRA.Repository.Context;

namespace Stone.Lancamentos.INFRA.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20220516171252_StoneLancamentosInfra")]
    partial class StoneLancamentosInfra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stone.Lancamentos.DOMINIO.Entities.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_referencia");

                    b.Property<string>("Estabelecimento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estabelecimento");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TB_LANCAMENTO");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataReferencia = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estabelecimento = "Padaria Stn",
                            FormaPagamento = 1,
                            Valor = 70m
                        },
                        new
                        {
                            Id = 2L,
                            DataReferencia = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estabelecimento = "Roupas Stn",
                            FormaPagamento = 2,
                            Valor = 1000m
                        },
                        new
                        {
                            Id = 3L,
                            DataReferencia = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estabelecimento = "Roupas Stn",
                            FormaPagamento = 2,
                            Valor = 1000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
